use station_protocol::*;

fn main() {
    let config = specta::ts::ExportConfiguration::default();

    let mut output = String::new();
    output.push_str("// Auto-generated by station-protocol crate. Do not edit.\n");
    output.push_str("// Run: cd crates/station-protocol && cargo run --bin export-types\n\n");

    for ts in [
        specta::ts::export::<StationEvent>(&config).unwrap(),
        specta::ts::export::<StationCommand>(&config).unwrap(),
        specta::ts::export::<PhasePlan>(&config).unwrap(),
        specta::ts::export::<PlugDefinition>(&config).unwrap(),
        specta::ts::export::<PhaseLogLine>(&config).unwrap(),
        specta::ts::export::<RunMeasurement>(&config).unwrap(),
        specta::ts::export::<UnitInfo>(&config).unwrap(),
        specta::ts::export::<ValidatorResult>(&config).unwrap(),
        specta::ts::export::<UiComponent>(&config).unwrap(),
        specta::ts::export::<UiOption>(&config).unwrap(),
        specta::ts::export::<ComponentType>(&config).unwrap(),
        specta::ts::export::<ComponentValue>(&config).unwrap(),
        specta::ts::export::<Screen>(&config).unwrap(),
        specta::ts::export::<RunUploadFailedKind>(&config).unwrap(),
        specta::ts::export::<RunUploadDroppedReason>(&config).unwrap(),
        specta::ts::export::<LogoutReason>(&config).unwrap(),
        specta::ts::export::<UiUpdateAction>(&config).unwrap(),
        specta::ts::export::<PhaseStage>(&config).unwrap(),
        specta::ts::export::<PlugStage>(&config).unwrap(),
        specta::ts::export::<PlugLifecycleStatus>(&config).unwrap(),
        specta::ts::export::<MeasurementOutcome>(&config).unwrap(),
        specta::ts::export::<RunOutcome>(&config).unwrap(),
        specta::ts::export::<TextSize>(&config).unwrap(),
        specta::ts::export::<TextColor>(&config).unwrap(),
        specta::ts::export::<FontFamily>(&config).unwrap(),
        specta::ts::export::<PresencePayload>(&config).unwrap(),
        specta::ts::export::<PresenceFocus>(&config).unwrap(),
        specta::ts::export::<PresenceDraft>(&config).unwrap(),
    ] {
        output.push_str(&ts);
        output.push('\n');
    }

    // Internal codegen tool: emits the TypeScript bindings for these wire
    // types. Output dir is taken from STATION_PROTOCOL_TS_OUT (the monorepo
    // points it at packages/shared/types/generated); defaults to the current
    // directory so a standalone run never writes outside the checkout.
    let out_dir = std::env::var("STATION_PROTOCOL_TS_OUT").unwrap_or_else(|_| ".".to_string());
    let out_dir = std::path::Path::new(&out_dir);
    std::fs::create_dir_all(out_dir).expect("create output dir");
    std::fs::write(out_dir.join("station-protocol.ts"), &output).expect("write TS types");

    println!("Exported to {}", out_dir.join("station-protocol.ts").display());
    print!("{output}");
}
