// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
use tofupilot_sdk::TofuPilot;
#[allow(unused_imports)]
use tofupilot_sdk::types::*;

/// Attachments commands.
#[derive(Subcommand)]
pub enum AttachmentsCommand {
    /// Initialize upload
    Initialize(InitializeArgs),
    /// Finalize upload
    Finalize(FinalizeArgs),
}

// ---------------------------------------------------------------------------
// Initialize
// ---------------------------------------------------------------------------

/// Initialize upload
#[derive(Args)]
pub struct InitializeArgs {
    /// File name including extension (e.g. "report.pdf")
    #[arg(long)]
    pub name: String,
}

// ---------------------------------------------------------------------------
// Finalize
// ---------------------------------------------------------------------------

/// Finalize upload
#[derive(Args)]
pub struct FinalizeArgs {
    /// ID of the upload to finalize
    #[arg(long)]
    pub id: String,
}


pub async fn execute(client: &TofuPilot, cmd: AttachmentsCommand, json_mode: bool) -> i32 {
    match cmd {
        AttachmentsCommand::Initialize(args) => execute_initialize(client, args, json_mode).await,
        AttachmentsCommand::Finalize(args) => execute_finalize(client, args, json_mode).await,
    }
}

async fn execute_initialize(client: &TofuPilot, args: InitializeArgs, json_mode: bool) -> i32 {
    let mut builder = client.attachments().initialize();
    builder = builder.name(&args.name);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_finalize(client: &TofuPilot, args: FinalizeArgs, json_mode: bool) -> i32 {
    let mut builder = client.attachments().finalize();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

