// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use crate::display;
use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Batches commands.
#[derive(Subcommand)]
pub enum BatchesCommand {
    /// Get batch
    Get(GetArgs),
    /// Delete batch
    Rm(RmArgs),
    /// Update batch
    Update(UpdateArgs),
    /// List and filter batches
    Ls(LsArgs),
    /// Create batch
    Create(CreateArgs),
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get batch
#[derive(Args)]
pub struct GetArgs {
    /// Number of the batch to retrieve.
    #[arg(long)]
    pub number: String,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete batch
#[derive(Args)]
pub struct RmArgs {
    /// number
    #[arg(long)]
    pub number: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update batch
#[derive(Args)]
pub struct UpdateArgs {
    /// Current batch number to update.
    #[arg(long)]
    pub number: String,
    /// New batch number.
    #[arg(long)]
    pub new_number: String,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter batches
#[derive(Args)]
pub struct LsArgs {
    /// ids
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
    /// numbers
    #[arg(long, num_args = 1..)]
    pub numbers: Option<Vec<String>>,
    /// created_after
    #[arg(long)]
    pub created_after: Option<String>,
    /// created_before
    #[arg(long)]
    pub created_before: Option<String>,
    /// Maximum number of batches to return. Use `cursor` to fetch additional results.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// part_numbers
    #[arg(long, num_args = 1..)]
    pub part_numbers: Option<Vec<String>>,
    /// revision_numbers
    #[arg(long, num_args = 1..)]
    pub revision_numbers: Option<Vec<String>>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create batch
#[derive(Args)]
pub struct CreateArgs {
    /// The batch number identifier
    #[arg(long)]
    pub number: String,
}

pub async fn execute(client: &TofuPilot, cmd: BatchesCommand, json_mode: bool) -> i32 {
    match cmd {
        BatchesCommand::Get(args) => execute_get(client, args, json_mode).await,
        BatchesCommand::Rm(args) => execute_delete(client, args, json_mode).await,
        BatchesCommand::Update(args) => execute_update(client, args, json_mode).await,
        BatchesCommand::Ls(args) => execute_list(client, args, json_mode).await,
        BatchesCommand::Create(args) => execute_create(client, args, json_mode).await,
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.batches().get();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.batches().delete();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Deleted batch{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.batches().update();
    builder = builder.number(&args.number);
    builder = builder.new_number(&args.new_number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Updated batch{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.batches().list();
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    if let Some(ref v) = args.numbers {
        builder = builder.numbers(v.clone());
    }
    if let Some(ref v) = args.created_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-before: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.part_numbers {
        builder = builder.part_numbers(v.clone());
    }
    if let Some(ref v) = args.revision_numbers {
        builder = builder.revision_numbers(v.clone());
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<BatchListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_by(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_order(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"]
                    .as_array()
                    .map(|a| a.as_slice())
                    .unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 8,
                        truncate: true,
                    },
                    display::Column {
                        header: "Number",
                        path: "number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Units",
                        path: "unit_count",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Created",
                        path: "created_at",
                        format: "relative",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.batches().create();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Created batch{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
