// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Deployments commands.
#[derive(Subcommand)]
pub enum DeploymentsCommand {
    /// List and filter deployments
    Ls(LsArgs),
    /// Get deployment
    Get(GetArgs),
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter deployments
#[derive(Args)]
pub struct LsArgs {
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
    /// environments
    #[arg(long, num_args = 1..)]
    pub environments: Option<Vec<String>>,
    /// build_statuses
    #[arg(long, num_args = 1..)]
    pub build_statuses: Option<Vec<String>>,
    /// pushed
    #[arg(long)]
    pub pushed: Option<bool>,
    /// branch_names
    #[arg(long, num_args = 1..)]
    pub branch_names: Option<Vec<String>>,
    /// author_usernames
    #[arg(long, num_args = 1..)]
    pub author_usernames: Option<Vec<String>>,
    /// deployed_after
    #[arg(long)]
    pub deployed_after: Option<String>,
    /// deployed_before
    #[arg(long)]
    pub deployed_before: Option<String>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// Maximum number of deployments to return.
    #[arg(long)]
    pub limit: Option<i64>,
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    #[arg(long)]
    pub cursor: Option<i64>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get deployment
#[derive(Args)]
pub struct GetArgs {
    /// The deployment ID to retrieve.
    #[arg(long)]
    pub id: String,
}

pub async fn execute(client: &TofuPilot, cmd: DeploymentsCommand, json_mode: bool) -> i32 {
    match cmd {
        DeploymentsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        DeploymentsCommand::Get(args) => execute_get(client, args, json_mode).await,
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.deployments().list();
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    if let Some(ref v) = args.environments {
        let mut parsed: Vec<Environment> = Vec::new();
        for s in v {
            match serde_json::from_value::<Environment>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --environments: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.environments(parsed);
    }
    if let Some(ref v) = args.build_statuses {
        let mut parsed: Vec<DeploymentGetStatus> = Vec::new();
        for s in v {
            match serde_json::from_value::<DeploymentGetStatus>(serde_json::Value::String(
                s.clone(),
            )) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --build-statuses: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.build_statuses(parsed);
    }
    if let Some(v) = args.pushed {
        builder = builder.pushed(v);
    }
    if let Some(ref v) = args.branch_names {
        builder = builder.branch_names(v.clone());
    }
    if let Some(ref v) = args.author_usernames {
        builder = builder.author_usernames(v.clone());
    }
    if let Some(ref v) = args.deployed_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.deployed_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --deployed-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.deployed_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.deployed_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --deployed-before: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.deployments().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
