// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
use tofupilot_sdk::TofuPilot;
#[allow(unused_imports)]
use tofupilot_sdk::types::*;

/// Imports commands.
#[derive(Subcommand)]
pub enum ImportsCommand {
    /// Import runs from structured files
    Structured(StructuredArgs),
    /// Import a run from a tabular file
    Tabular(TabularArgs),
}

// ---------------------------------------------------------------------------
// Structured
// ---------------------------------------------------------------------------

/// Import runs from structured files
#[derive(Args)]
pub struct StructuredArgs {
    /// Files to import (1–100). Pass a single-item list to import one file. Each item is parsed independently; one failure does not abort the others. (JSON string)
    #[arg(long)]
    pub items: String,
}

// ---------------------------------------------------------------------------
// Tabular
// ---------------------------------------------------------------------------

/// Import a run from a tabular file
#[derive(Args)]
pub struct TabularArgs {
    /// ID of a previously uploaded tabular file.
    #[arg(long)]
    pub upload_id: String,
    /// Procedure to attach the imported run to. Always overrides any procedure referenced in the file. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
    #[arg(long)]
    pub procedure_id: String,
    /// Inline column mapping describing how source columns feed TofuPilot fields. Provide this OR template_id, not both. (JSON string)
    #[arg(long)]
    pub mapping: Option<String>,
    /// ID of a saved mapping template to apply. Provide this OR mapping, not both.
    #[arg(long)]
    pub template_id: Option<String>,
}


pub async fn execute(client: &TofuPilot, cmd: ImportsCommand, json_mode: bool) -> i32 {
    match cmd {
        ImportsCommand::Structured(args) => execute_structured(client, args, json_mode).await,
        ImportsCommand::Tabular(args) => execute_tabular(client, args, json_mode).await,
    }
}

async fn execute_structured(client: &TofuPilot, args: StructuredArgs, json_mode: bool) -> i32 {
    let mut builder = client.imports().structured();
    match serde_json::from_str::<Vec<ImportStructuredItems>>(&args.items) {
        Ok(parsed) => { builder = builder.items(parsed); }
        Err(e) => {
            eprintln!("Invalid JSON for --items: {e}");
            return 1;
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_tabular(client: &TofuPilot, args: TabularArgs, json_mode: bool) -> i32 {
    let mut builder = client.imports().tabular();
    builder = builder.upload_id(&args.upload_id);
    builder = builder.procedure_id(&args.procedure_id);
    if let Some(ref v) = args.mapping {
        match serde_json::from_str::<ImportTabularMapping>(v) {
            Ok(parsed) => { builder = builder.mapping(parsed); }
            Err(e) => {
                eprintln!("Invalid JSON for --mapping: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.template_id {
        builder = builder.template_id(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

