// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
use tofupilot_sdk::TofuPilot;
#[allow(unused_imports)]
use tofupilot_sdk::types::*;

/// Logs commands.
#[derive(Subcommand)]
pub enum LogsCommand {
    /// List and filter logs
    Ls(LsArgs),
    /// Get log
    Get(GetArgs),
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter logs
#[derive(Args)]
pub struct LsArgs {
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// levels
    #[arg(long, num_args = 1..)]
    pub levels: Option<Vec<String>>,
    /// Filter logs with timestamp after this date (inclusive).
    #[arg(long)]
    pub timestamp_after: Option<String>,
    /// Filter logs with timestamp before this date (inclusive).
    #[arg(long)]
    pub timestamp_before: Option<String>,
    /// source_files
    #[arg(long, num_args = 1..)]
    pub source_files: Option<Vec<String>>,
    /// run_ids
    #[arg(long, num_args = 1..)]
    pub run_ids: Option<Vec<String>>,
    /// run_outcomes
    #[arg(long, num_args = 1..)]
    pub run_outcomes: Option<Vec<String>>,
    /// procedure_versions
    #[arg(long, num_args = 1..)]
    pub procedure_versions: Option<Vec<String>>,
    /// deployment_ids
    #[arg(long, num_args = 1..)]
    pub deployment_ids: Option<Vec<String>>,
    /// environments
    #[arg(long, num_args = 1..)]
    pub environments: Option<Vec<String>>,
    /// serial_numbers
    #[arg(long, num_args = 1..)]
    pub serial_numbers: Option<Vec<String>>,
    /// part_numbers
    #[arg(long, num_args = 1..)]
    pub part_numbers: Option<Vec<String>>,
    /// revision_numbers
    #[arg(long, num_args = 1..)]
    pub revision_numbers: Option<Vec<String>>,
    /// batch_numbers
    #[arg(long, num_args = 1..)]
    pub batch_numbers: Option<Vec<String>>,
    /// samples
    #[arg(long, num_args = 1..)]
    pub samples: Option<Vec<String>>,
    /// created_by_station_ids
    #[arg(long, num_args = 1..)]
    pub created_by_station_ids: Option<Vec<String>>,
    /// created_by_user_ids
    #[arg(long, num_args = 1..)]
    pub created_by_user_ids: Option<Vec<String>>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
    /// Maximum number of logs to return.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get log
#[derive(Args)]
pub struct GetArgs {
    /// Unique identifier for the log entry.
    #[arg(long)]
    pub id: String,
}


pub async fn execute(client: &TofuPilot, cmd: LogsCommand, json_mode: bool) -> i32 {
    match cmd {
        LogsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        LogsCommand::Get(args) => execute_get(client, args, json_mode).await,
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.logs().list();
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.levels {
        let mut parsed: Vec<Level> = Vec::new();
        for s in v {
            match serde_json::from_value::<Level>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --levels: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.levels(parsed);
    }
    if let Some(ref v) = args.timestamp_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => { builder = builder.timestamp_after(dt); }
            Err(e) => {
                eprintln!("Invalid datetime for --timestamp-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.timestamp_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => { builder = builder.timestamp_before(dt); }
            Err(e) => {
                eprintln!("Invalid datetime for --timestamp-before: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.source_files {
        builder = builder.source_files(v.clone());
    }
    if let Some(ref v) = args.run_ids {
        builder = builder.run_ids(v.clone());
    }
    if let Some(ref v) = args.run_outcomes {
        let mut parsed: Vec<LogGetOutcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<LogGetOutcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --run-outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.run_outcomes(parsed);
    }
    if let Some(ref v) = args.procedure_versions {
        builder = builder.procedure_versions(v.clone());
    }
    if let Some(ref v) = args.deployment_ids {
        builder = builder.deployment_ids(v.clone());
    }
    if let Some(ref v) = args.environments {
        let mut parsed: Vec<Environment> = Vec::new();
        for s in v {
            match serde_json::from_value::<Environment>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --environments: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.environments(parsed);
    }
    if let Some(ref v) = args.serial_numbers {
        builder = builder.serial_numbers(v.clone());
    }
    if let Some(ref v) = args.part_numbers {
        builder = builder.part_numbers(v.clone());
    }
    if let Some(ref v) = args.revision_numbers {
        builder = builder.revision_numbers(v.clone());
    }
    if let Some(ref v) = args.batch_numbers {
        builder = builder.batch_numbers(v.clone());
    }
    if let Some(ref v) = args.samples {
        let mut parsed: Vec<Sample> = Vec::new();
        for s in v {
            match serde_json::from_value::<Sample>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --samples: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.samples(parsed);
    }
    if let Some(ref v) = args.created_by_station_ids {
        builder = builder.created_by_station_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_user_ids {
        builder = builder.created_by_user_ids(v.clone());
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<LogListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => { builder = builder.sort_by(parsed); }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => { builder = builder.sort_order(parsed); }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.logs().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

