// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Measurements commands.
#[derive(Subcommand)]
pub enum MeasurementsCommand {
    /// List and filter measurements
    Ls(LsArgs),
    /// Get measurement
    Get(GetArgs),
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter measurements
#[derive(Args)]
pub struct LsArgs {
    /// Procedure to list measurements for. Required: measurements are scoped to a single procedure.
    #[arg(long)]
    pub procedure_id: Option<String>,
    /// phase_name
    #[arg(long)]
    pub phase_name: Option<String>,
    /// measurement_name
    #[arg(long)]
    pub measurement_name: Option<String>,
    /// phase_names
    #[arg(long, num_args = 1..)]
    pub phase_names: Option<Vec<String>>,
    /// outcomes
    #[arg(long, num_args = 1..)]
    pub outcomes: Option<Vec<String>>,
    /// ids
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
    /// duration_min
    #[arg(long)]
    pub duration_min: Option<String>,
    /// duration_max
    #[arg(long)]
    pub duration_max: Option<String>,
    /// deployment_ids
    #[arg(long, num_args = 1..)]
    pub deployment_ids: Option<Vec<String>>,
    /// procedure_versions
    #[arg(long, num_args = 1..)]
    pub procedure_versions: Option<Vec<String>>,
    /// environments
    #[arg(long, num_args = 1..)]
    pub environments: Option<Vec<String>>,
    /// serial_numbers
    #[arg(long, num_args = 1..)]
    pub serial_numbers: Option<Vec<String>>,
    /// part_numbers
    #[arg(long, num_args = 1..)]
    pub part_numbers: Option<Vec<String>>,
    /// revision_numbers
    #[arg(long, num_args = 1..)]
    pub revision_numbers: Option<Vec<String>>,
    /// batch_numbers
    #[arg(long, num_args = 1..)]
    pub batch_numbers: Option<Vec<String>>,
    /// operated_by_ids
    #[arg(long, num_args = 1..)]
    pub operated_by_ids: Option<Vec<String>>,
    /// created_by_station_ids
    #[arg(long, num_args = 1..)]
    pub created_by_station_ids: Option<Vec<String>>,
    /// created_by_user_ids
    #[arg(long, num_args = 1..)]
    pub created_by_user_ids: Option<Vec<String>>,
    /// started_after
    #[arg(long)]
    pub started_after: Option<String>,
    /// started_before
    #[arg(long)]
    pub started_before: Option<String>,
    /// Exclude retried phase attempts, keeping only the final attempt.
    #[arg(long)]
    pub exclude_retries: Option<bool>,
    /// value_min
    #[arg(long)]
    pub value_min: Option<f64>,
    /// value_max
    #[arg(long)]
    pub value_max: Option<f64>,
    /// value_bool
    #[arg(long)]
    pub value_bool: Option<bool>,
    /// value_strings
    #[arg(long, num_args = 1..)]
    pub value_strings: Option<Vec<String>>,
    /// measurement_outcomes
    #[arg(long, num_args = 1..)]
    pub measurement_outcomes: Option<Vec<String>>,
    /// measurement_types
    #[arg(long, num_args = 1..)]
    pub measurement_types: Option<Vec<String>>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
    /// Maximum number of measurements to return.
    #[arg(long)]
    pub limit: Option<i64>,
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    #[arg(long)]
    pub cursor: Option<i64>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get measurement
#[derive(Args)]
pub struct GetArgs {
    /// ID of the measurement to retrieve.
    #[arg(long)]
    pub id: String,
}

pub async fn execute(client: &TofuPilot, cmd: MeasurementsCommand, json_mode: bool) -> i32 {
    match cmd {
        MeasurementsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        MeasurementsCommand::Get(args) => execute_get(client, args, json_mode).await,
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.measurements().list();
    if let Some(ref v) = args.procedure_id {
        builder = builder.procedure_id(v);
    }
    if let Some(ref v) = args.phase_name {
        builder = builder.phase_name(v);
    }
    if let Some(ref v) = args.measurement_name {
        builder = builder.measurement_name(v);
    }
    if let Some(ref v) = args.phase_names {
        builder = builder.phase_names(v.clone());
    }
    if let Some(ref v) = args.outcomes {
        let mut parsed: Vec<LogGetOutcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<LogGetOutcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.outcomes(parsed);
    }
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    if let Some(ref v) = args.duration_min {
        builder = builder.duration_min(v);
    }
    if let Some(ref v) = args.duration_max {
        builder = builder.duration_max(v);
    }
    if let Some(ref v) = args.deployment_ids {
        builder = builder.deployment_ids(v.clone());
    }
    if let Some(ref v) = args.procedure_versions {
        builder = builder.procedure_versions(v.clone());
    }
    if let Some(ref v) = args.environments {
        let mut parsed: Vec<Environment> = Vec::new();
        for s in v {
            match serde_json::from_value::<Environment>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --environments: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.environments(parsed);
    }
    if let Some(ref v) = args.serial_numbers {
        builder = builder.serial_numbers(v.clone());
    }
    if let Some(ref v) = args.part_numbers {
        builder = builder.part_numbers(v.clone());
    }
    if let Some(ref v) = args.revision_numbers {
        builder = builder.revision_numbers(v.clone());
    }
    if let Some(ref v) = args.batch_numbers {
        builder = builder.batch_numbers(v.clone());
    }
    if let Some(ref v) = args.operated_by_ids {
        builder = builder.operated_by_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_station_ids {
        builder = builder.created_by_station_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_user_ids {
        builder = builder.created_by_user_ids(v.clone());
    }
    if let Some(ref v) = args.started_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.started_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --started-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.started_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.started_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --started-before: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.exclude_retries {
        builder = builder.exclude_retries(v);
    }
    if let Some(v) = args.value_min {
        builder = builder.value_min(v);
    }
    if let Some(v) = args.value_max {
        builder = builder.value_max(v);
    }
    if let Some(v) = args.value_bool {
        builder = builder.value_bool(v);
    }
    if let Some(ref v) = args.value_strings {
        builder = builder.value_strings(v.clone());
    }
    if let Some(ref v) = args.measurement_outcomes {
        let mut parsed: Vec<Outcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<Outcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --measurement-outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.measurement_outcomes(parsed);
    }
    if let Some(ref v) = args.measurement_types {
        let mut parsed: Vec<MeasurementType> = Vec::new();
        for s in v {
            match serde_json::from_value::<MeasurementType>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --measurement-types: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.measurement_types(parsed);
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<MeasurementListSortBy>(serde_json::Value::String(v.clone()))
        {
            Ok(parsed) => {
                builder = builder.sort_by(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_order(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.measurements().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
