// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use crate::display;
use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Parts commands.
#[derive(Subcommand)]
pub enum PartsCommand {
    /// Create part
    Create(CreateArgs),
    /// List and filter parts
    Ls(LsArgs),
    /// Get part
    Get(GetArgs),
    /// Update part
    Update(UpdateArgs),
    /// Delete part
    Rm(RmArgs),
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create part
#[derive(Args)]
pub struct CreateArgs {
    /// Unique identifier number for the part.
    #[arg(long)]
    pub number: String,
    /// Human-readable name for the part. If not provided, a default name will be used.
    #[arg(long)]
    pub name: Option<String>,
    /// Revision identifier for the part version. If not provided, default revision identifier will be used.
    #[arg(long)]
    pub revision_number: Option<String>,
    /// Custom metadata to attach to the part (max 50 keys per part). Plain object of key/value pairs; values can be string, number, or boolean. Type is detected from the value. (JSON string)
    #[arg(long)]
    pub metadata: Option<String>,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter parts
#[derive(Args)]
pub struct LsArgs {
    /// Maximum number of parts to return in a single page.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
    /// Filter parts by custom metadata. Supports up to 5 keys per request. Per-key operators: string `{in: [...]}`/`{contains: "..."}`, number `{gte, lte, gt, lt, eq}`, bool `{eq: true|false}`.
    #[arg(long)]
    pub metadata: Option<String>,
    /// When true, includes the custom metadata object on each part in the response. Defaults to false to keep payloads small.
    #[arg(long)]
    pub include_metadata: Option<bool>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get part
#[derive(Args)]
pub struct GetArgs {
    /// Part number of the part to retrieve.
    #[arg(long)]
    pub number: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update part
#[derive(Args)]
pub struct UpdateArgs {
    /// Part number of the part to update.
    #[arg(long)]
    pub number: String,
    /// New unique identifier number for the part.
    #[arg(long)]
    pub new_number: Option<String>,
    /// New human-readable name for the part.
    #[arg(long)]
    pub name: Option<String>,
    /// Custom metadata to upsert on the part. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key. (JSON string)
    #[arg(long)]
    pub metadata: Option<String>,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete part
#[derive(Args)]
pub struct RmArgs {
    /// Part number to delete.
    #[arg(long)]
    pub number: String,
}

pub async fn execute(client: &TofuPilot, cmd: PartsCommand, json_mode: bool) -> i32 {
    match cmd {
        PartsCommand::Create(args) => execute_create(client, args, json_mode).await,
        PartsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        PartsCommand::Get(args) => execute_get(client, args, json_mode).await,
        PartsCommand::Update(args) => execute_update(client, args, json_mode).await,
        PartsCommand::Rm(args) => execute_delete(client, args, json_mode).await,
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().create();
    builder = builder.number(&args.number);
    if let Some(ref v) = args.name {
        builder = builder.name(v);
    }
    if let Some(ref v) = args.revision_number {
        builder = builder.revision_number(v);
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Created part{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().list();
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<PartListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_by(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_order(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.include_metadata {
        builder = builder.include_metadata(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"]
                    .as_array()
                    .map(|a| a.as_slice())
                    .unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Number",
                        path: "number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Name",
                        path: "name",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Created",
                        path: "created_at",
                        format: "relative",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().get();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().update();
    builder = builder.number(&args.number);
    if let Some(ref v) = args.new_number {
        builder = builder.new_number(v);
    }
    if let Some(ref v) = args.name {
        builder = builder.name(v);
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Updated part{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().delete();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Deleted part{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
