// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
use tofupilot_sdk::TofuPilot;
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use crate::display;

/// Parts commands.
#[derive(Subcommand)]
pub enum PartsCommand {
    /// Create part
    Create(CreateArgs),
    /// List and filter parts
    Ls(LsArgs),
    /// Get part
    Get(GetArgs),
    /// Update part
    Update(UpdateArgs),
    /// Delete part
    Rm(RmArgs),
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create part
#[derive(Args)]
pub struct CreateArgs {
    /// Unique identifier number for the part.
    #[arg(long)]
    pub number: String,
    /// Human-readable name for the part. If not provided, a default name will be used.
    #[arg(long)]
    pub name: Option<String>,
    /// Revision identifier for the part version. If not provided, default revision identifier will be used.
    #[arg(long)]
    pub revision_number: Option<String>,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter parts
#[derive(Args)]
pub struct LsArgs {
    /// Maximum number of parts to return in a single page.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get part
#[derive(Args)]
pub struct GetArgs {
    /// Part number of the part to retrieve.
    #[arg(long)]
    pub number: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update part
#[derive(Args)]
pub struct UpdateArgs {
    /// Part number of the part to update.
    #[arg(long)]
    pub number: String,
    /// New unique identifier number for the part.
    #[arg(long)]
    pub new_number: Option<String>,
    /// New human-readable name for the part.
    #[arg(long)]
    pub name: Option<String>,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete part
#[derive(Args)]
pub struct RmArgs {
    /// Part number to delete.
    #[arg(long)]
    pub number: String,
}


pub async fn execute(client: &TofuPilot, cmd: PartsCommand, json_mode: bool) -> i32 {
    match cmd {
        PartsCommand::Create(args) => execute_create(client, args, json_mode).await,
        PartsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        PartsCommand::Get(args) => execute_get(client, args, json_mode).await,
        PartsCommand::Update(args) => execute_update(client, args, json_mode).await,
        PartsCommand::Rm(args) => execute_delete(client, args, json_mode).await,
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().create();
    builder = builder.number(&args.number);
    if let Some(ref v) = args.name {
        builder = builder.name(v);
    }
    if let Some(ref v) = args.revision_number {
        builder = builder.revision_number(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().list();
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<PartListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => { builder = builder.sort_by(parsed); }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => { builder = builder.sort_order(parsed); }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"].as_array().map(|a| a.as_slice()).unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 8,
                        truncate: true,
                    },
                    display::Column {
                        header: "Number",
                        path: "number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Name",
                        path: "name",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Created",
                        path: "created_at",
                        format: "relative",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().get();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().update();
    builder = builder.number(&args.number);
    if let Some(ref v) = args.new_number {
        builder = builder.new_number(v);
    }
    if let Some(ref v) = args.name {
        builder = builder.name(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.parts().delete();
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

