// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
use tofupilot_sdk::TofuPilot;
#[allow(unused_imports)]
use tofupilot_sdk::types::*;

/// Phases commands.
#[derive(Subcommand)]
pub enum PhasesCommand {
    /// List and filter phases
    Ls(LsArgs),
    /// Get phase
    Get(GetArgs),
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter phases
#[derive(Args)]
pub struct LsArgs {
    /// Procedure to list phases for. Required: phases are scoped to a single procedure.
    #[arg(long)]
    pub procedure_id: Option<String>,
    /// names
    #[arg(long, num_args = 1..)]
    pub names: Option<Vec<String>>,
    /// outcomes
    #[arg(long, num_args = 1..)]
    pub outcomes: Option<Vec<String>>,
    /// started_after
    #[arg(long)]
    pub started_after: Option<String>,
    /// started_before
    #[arg(long)]
    pub started_before: Option<String>,
    /// exclude_retries
    #[arg(long)]
    pub exclude_retries: Option<bool>,
    /// run_outcomes
    #[arg(long, num_args = 1..)]
    pub run_outcomes: Option<Vec<String>>,
    /// ids
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
    /// duration_min
    #[arg(long)]
    pub duration_min: Option<String>,
    /// duration_max
    #[arg(long)]
    pub duration_max: Option<String>,
    /// deployment_ids
    #[arg(long, num_args = 1..)]
    pub deployment_ids: Option<Vec<String>>,
    /// procedure_versions
    #[arg(long, num_args = 1..)]
    pub procedure_versions: Option<Vec<String>>,
    /// environments
    #[arg(long, num_args = 1..)]
    pub environments: Option<Vec<String>>,
    /// operated_by_ids
    #[arg(long, num_args = 1..)]
    pub operated_by_ids: Option<Vec<String>>,
    /// created_by_station_ids
    #[arg(long, num_args = 1..)]
    pub created_by_station_ids: Option<Vec<String>>,
    /// created_by_user_ids
    #[arg(long, num_args = 1..)]
    pub created_by_user_ids: Option<Vec<String>>,
    /// serial_numbers
    #[arg(long, num_args = 1..)]
    pub serial_numbers: Option<Vec<String>>,
    /// part_numbers
    #[arg(long, num_args = 1..)]
    pub part_numbers: Option<Vec<String>>,
    /// revision_numbers
    #[arg(long, num_args = 1..)]
    pub revision_numbers: Option<Vec<String>>,
    /// batch_numbers
    #[arg(long, num_args = 1..)]
    pub batch_numbers: Option<Vec<String>>,
    /// samples
    #[arg(long, num_args = 1..)]
    pub samples: Option<Vec<String>>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
    /// Maximum number of phases to return.
    #[arg(long)]
    pub limit: Option<i64>,
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    #[arg(long)]
    pub cursor: Option<i64>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get phase
#[derive(Args)]
pub struct GetArgs {
    /// ID of the phase to retrieve.
    #[arg(long)]
    pub id: String,
}


pub async fn execute(client: &TofuPilot, cmd: PhasesCommand, json_mode: bool) -> i32 {
    match cmd {
        PhasesCommand::Ls(args) => execute_list(client, args, json_mode).await,
        PhasesCommand::Get(args) => execute_get(client, args, json_mode).await,
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.phases().list();
    if let Some(ref v) = args.procedure_id {
        builder = builder.procedure_id(v);
    }
    if let Some(ref v) = args.names {
        builder = builder.names(v.clone());
    }
    if let Some(ref v) = args.outcomes {
        let mut parsed: Vec<PhaseGetOutcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<PhaseGetOutcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.outcomes(parsed);
    }
    if let Some(ref v) = args.started_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => { builder = builder.started_after(dt); }
            Err(e) => {
                eprintln!("Invalid datetime for --started-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.started_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => { builder = builder.started_before(dt); }
            Err(e) => {
                eprintln!("Invalid datetime for --started-before: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.exclude_retries {
        builder = builder.exclude_retries(v);
    }
    if let Some(ref v) = args.run_outcomes {
        let mut parsed: Vec<LogGetOutcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<LogGetOutcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --run-outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.run_outcomes(parsed);
    }
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    if let Some(ref v) = args.duration_min {
        builder = builder.duration_min(v);
    }
    if let Some(ref v) = args.duration_max {
        builder = builder.duration_max(v);
    }
    if let Some(ref v) = args.deployment_ids {
        builder = builder.deployment_ids(v.clone());
    }
    if let Some(ref v) = args.procedure_versions {
        builder = builder.procedure_versions(v.clone());
    }
    if let Some(ref v) = args.environments {
        let mut parsed: Vec<Environment> = Vec::new();
        for s in v {
            match serde_json::from_value::<Environment>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --environments: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.environments(parsed);
    }
    if let Some(ref v) = args.operated_by_ids {
        builder = builder.operated_by_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_station_ids {
        builder = builder.created_by_station_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_user_ids {
        builder = builder.created_by_user_ids(v.clone());
    }
    if let Some(ref v) = args.serial_numbers {
        builder = builder.serial_numbers(v.clone());
    }
    if let Some(ref v) = args.part_numbers {
        builder = builder.part_numbers(v.clone());
    }
    if let Some(ref v) = args.revision_numbers {
        builder = builder.revision_numbers(v.clone());
    }
    if let Some(ref v) = args.batch_numbers {
        builder = builder.batch_numbers(v.clone());
    }
    if let Some(ref v) = args.samples {
        let mut parsed: Vec<PhaseListQueryParamSample> = Vec::new();
        for s in v {
            match serde_json::from_value::<PhaseListQueryParamSample>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --samples: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.samples(parsed);
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<PhaseListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => { builder = builder.sort_by(parsed); }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => { builder = builder.sort_order(parsed); }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.phases().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

