// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use crate::display;
use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Procedures commands.
#[derive(Subcommand)]
pub enum ProceduresCommand {
    /// Create procedure
    Create(CreateArgs),
    /// List and filter procedures
    Ls(LsArgs),
    /// Get procedure
    Get(GetArgs),
    /// Delete procedure
    Rm(RmArgs),
    /// Update procedure
    Update(UpdateArgs),
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create procedure
#[derive(Args)]
pub struct CreateArgs {
    /// Name of the procedure. Must be unique within the organization.
    #[arg(long)]
    pub name: String,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter procedures
#[derive(Args)]
pub struct LsArgs {
    /// Maximum number of procedures to return per page.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<f64>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// created_after
    #[arg(long)]
    pub created_after: Option<String>,
    /// created_before
    #[arg(long)]
    pub created_before: Option<String>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get procedure
#[derive(Args)]
pub struct GetArgs {
    /// Unique identifier of the procedure to retrieve.
    #[arg(long)]
    pub id: String,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete procedure
#[derive(Args)]
pub struct RmArgs {
    /// Unique identifier of the procedure to delete.
    #[arg(long)]
    pub id: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update procedure
#[derive(Args)]
pub struct UpdateArgs {
    /// Unique identifier of the procedure to update.
    #[arg(long)]
    pub id: String,
    /// New name for the procedure.
    #[arg(long)]
    pub name: Option<String>,
    /// Branch treated as production. Pushes to this branch deploy as production; every other branch deploys as preview. Null = no branch promoted to production.
    #[arg(long)]
    pub production_branch: Option<String>,
    /// Master switch for auto-pushing builds to linked stations. Build artifacts are always recorded; this only gates the station fan-out.
    #[arg(long)]
    pub auto_push_enabled: Option<bool>,
    /// Branches matching any of these patterns (exact name or minimatch glob, e.g. "renovate/*") skip preview deployments. Empty array = no exclusions.
    #[arg(long, num_args = 1..)]
    pub excluded_branch_patterns: Option<Vec<String>>,
    /// Path within the linked repo to the directory holding this procedure's `pyproject.toml` (and `procedure.yaml` for framework procedures). Empty/null = repo root.
    #[arg(long)]
    pub root_directory: Option<String>,
    /// Entry-point path inside the procedure's package dir, relative to it. Forwarded to the CLI through the deployment manifest. Empty/null = use the framework default (openhtf/plain → main.py, pytest → ".", yaml → procedure.yaml auto-discovery).
    #[arg(long)]
    pub entry_point: Option<String>,
}

pub async fn execute(client: &TofuPilot, cmd: ProceduresCommand, json_mode: bool) -> i32 {
    match cmd {
        ProceduresCommand::Create(args) => execute_create(client, args, json_mode).await,
        ProceduresCommand::Ls(args) => execute_list(client, args, json_mode).await,
        ProceduresCommand::Get(args) => execute_get(client, args, json_mode).await,
        ProceduresCommand::Rm(args) => execute_delete(client, args, json_mode).await,
        ProceduresCommand::Update(args) => execute_update(client, args, json_mode).await,
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.procedures().create();
    builder = builder.name(&args.name);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Created procedure{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.procedures().list();
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.created_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-before: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"]
                    .as_array()
                    .map(|a| a.as_slice())
                    .unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 8,
                        truncate: true,
                    },
                    display::Column {
                        header: "Name",
                        path: "name",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Created",
                        path: "created_at",
                        format: "relative",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.procedures().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.procedures().delete();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Deleted procedure{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.procedures().update();
    builder = builder.id(&args.id);
    if let Some(ref v) = args.name {
        builder = builder.name(v);
    }
    if let Some(ref v) = args.production_branch {
        builder = builder.production_branch(v);
    }
    if let Some(v) = args.auto_push_enabled {
        builder = builder.auto_push_enabled(v);
    }
    if let Some(ref v) = args.excluded_branch_patterns {
        builder = builder.excluded_branch_patterns(v.clone());
    }
    if let Some(ref v) = args.root_directory {
        builder = builder.root_directory(v);
    }
    if let Some(ref v) = args.entry_point {
        builder = builder.entry_point(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Updated procedure{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
