// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Revisions commands.
#[derive(Subcommand)]
pub enum RevisionsCommand {
    /// Get part revision
    Get(GetArgs),
    /// Update part revision
    Update(UpdateArgs),
    /// Delete part revision
    Rm(RmArgs),
    /// Create part revision
    Create(CreateArgs),
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get part revision
#[derive(Args)]
pub struct GetArgs {
    /// Part number that the revision belongs to.
    #[arg(long)]
    pub part_number: String,
    /// Revision number to retrieve.
    #[arg(long)]
    pub revision_number: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update part revision
#[derive(Args)]
pub struct UpdateArgs {
    /// Part number that the revision belongs to.
    #[arg(long)]
    pub part_number: String,
    /// Current revision number to update.
    #[arg(long)]
    pub revision_number: String,
    /// New revision number to set.
    #[arg(long)]
    pub number: Option<String>,
    /// Upload ID for the revision image, or empty string to remove image
    #[arg(long)]
    pub image_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete part revision
#[derive(Args)]
pub struct RmArgs {
    /// Part number that the revision belongs to.
    #[arg(long)]
    pub part_number: String,
    /// Revision number to delete.
    #[arg(long)]
    pub revision_number: String,
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create part revision
#[derive(Args)]
pub struct CreateArgs {
    /// Part number to create a revision for.
    #[arg(long)]
    pub part_number: String,
    /// Revision number (e.g., version number or code).
    #[arg(long)]
    pub number: String,
}

pub async fn execute(client: &TofuPilot, cmd: RevisionsCommand, json_mode: bool) -> i32 {
    match cmd {
        RevisionsCommand::Get(args) => execute_get(client, args, json_mode).await,
        RevisionsCommand::Update(args) => execute_update(client, args, json_mode).await,
        RevisionsCommand::Rm(args) => execute_delete(client, args, json_mode).await,
        RevisionsCommand::Create(args) => execute_create(client, args, json_mode).await,
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.revisions().get();
    builder = builder.part_number(&args.part_number);
    builder = builder.revision_number(&args.revision_number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.revisions().update();
    builder = builder.part_number(&args.part_number);
    builder = builder.revision_number(&args.revision_number);
    if let Some(ref v) = args.number {
        builder = builder.number(v);
    }
    if let Some(ref v) = args.image_id {
        builder = builder.image_id(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.revisions().delete();
    builder = builder.part_number(&args.part_number);
    builder = builder.revision_number(&args.revision_number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.revisions().create();
    builder = builder.part_number(&args.part_number);
    builder = builder.number(&args.number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}
