// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use crate::display;
use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Runs commands.
#[derive(Subcommand)]
pub enum RunsCommand {
    /// Create run
    Create(CreateArgs),
    /// List and filter runs
    Ls(LsArgs),
    /// Delete runs
    Rm(RmArgs),
    /// Get run
    Get(GetArgs),
    /// Update run
    Update(UpdateArgs),
    /// Attach file to run
    CreateAttachment(CreateAttachmentArgs),
    /// Update run metadata
    UpdateMetadata(UpdateMetadataArgs),
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create run
#[derive(Args)]
pub struct CreateArgs {
    /// Overall test result. Use PASS when test succeeds, FAIL when test fails but script execution completed successfully, ERROR when script execution fails, TIMEOUT when test exceeds time limit, ABORTED for manual script interruption.
    #[arg(long)]
    pub outcome: String,
    /// Procedure ID. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
    #[arg(long)]
    pub procedure_id: String,
    /// Deployment ID this run was executed from. Set by the CLI when running a pulled deployment so the run is linked back to the exact build it ran. Validated against the procedure; left null for ad-hoc or local runs.
    #[arg(long)]
    pub deployment_id: Option<String>,
    /// Specific version of the test procedure used for the run. Matched case-insensitively. If none exist, a procedure with this procedure version will be created. If no procedure version is specified, the run will not be linked to any specific version.
    #[arg(long)]
    pub procedure_version: Option<String>,
    /// Email address of the operator who executed the test run. Honored only for API-key callers (user keys and station keys); browser session callers are auto-stamped with the session user and this field is ignored. If the email does not match a member of the calling organization, it is silently dropped and the run is recorded with no operator. The run is linked to this user (when resolved) to track who performed the test.
    #[arg(long)]
    pub operated_by: Option<String>,
    /// ISO 8601 timestamp when the test run began execution. This timestamp will be used to track when the test execution started and for historical analysis of test runs. A separate created_at timestamp is stored internally server side to track upload date. (ISO 8601)
    #[arg(long)]
    pub started_at: String,
    /// ISO 8601 timestamp when the test run finished execution. (ISO 8601)
    #[arg(long)]
    pub ended_at: String,
    /// Unique serial number of the unit under test. Matched case-insensitively. If no unit with this serial number exists, one will be created.
    #[arg(long)]
    pub serial_number: String,
    /// Component part number for the unit. Matched case-insensitively. This field is required if the part number cannot be extracted from the serial number (as set in the settings). This field takes precedence over extraction from serial number. A component with the provided or extracted part number will be created if one does not exist.
    #[arg(long)]
    pub part_number: Option<String>,
    /// Hardware revision identifier for the unit. Matched case-insensitively. If none exist, a revision with this number will be created. If no revision is specified, the unit will be linked to the default revision of the part number.
    #[arg(long)]
    pub revision_number: Option<String>,
    /// Production batch identifier for grouping units manufactured together. Matched case-insensitively. If none exist, a batch with this batch number will be created. If no batch number is specified, the unit will not be linked to any batch.
    #[arg(long)]
    pub batch_number: Option<String>,
    /// Array of sub-unit serial numbers that are part of this main unit. Matched case-insensitively. Each sub-unit must already exist and will be linked as a sub-component of the main unit under test. If no sub-units are specified, the unit will be created without sub-unit relationships.
    #[arg(long, num_args = 1..)]
    pub sub_units: Option<Vec<String>>,
    /// Additional notes or documentation about this test run.
    #[arg(long)]
    pub docstring: Option<String>,
    /// Array of test phases with measurements and results. Each phase represents a distinct stage of the test execution with timing information, outcome status, and optional measurements. If no phases are specified, the run will be created without phase-level organization of test data. (JSON string)
    #[arg(long)]
    pub phases: Option<String>,
    /// Array of log messages generated during the test execution. Each log entry captures events, errors, and diagnostic information with severity levels and source code references. If no logs are specified, the run will be created without log entries. (JSON string)
    #[arg(long)]
    pub logs: Option<String>,
    /// Custom metadata to attach to the run (max 50 keys). Plain object of key/value pairs; values can be string, number, or boolean. Type is detected from the value. (JSON string)
    #[arg(long)]
    pub metadata: Option<String>,
    /// Custom metadata to upsert on the unit under test (max 50 keys per unit). PATCH semantics: keys not present here are preserved on the unit. (JSON string)
    #[arg(long)]
    pub unit_metadata: Option<String>,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter runs
#[derive(Args)]
pub struct LsArgs {
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// ids
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
    /// outcomes
    #[arg(long, num_args = 1..)]
    pub outcomes: Option<Vec<String>>,
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
    /// procedure_versions
    #[arg(long, num_args = 1..)]
    pub procedure_versions: Option<Vec<String>>,
    /// deployment_ids
    #[arg(long, num_args = 1..)]
    pub deployment_ids: Option<Vec<String>>,
    /// environments
    #[arg(long, num_args = 1..)]
    pub environments: Option<Vec<String>>,
    /// serial_numbers
    #[arg(long, num_args = 1..)]
    pub serial_numbers: Option<Vec<String>>,
    /// samples
    #[arg(long, num_args = 1..)]
    pub samples: Option<Vec<String>>,
    /// part_numbers
    #[arg(long, num_args = 1..)]
    pub part_numbers: Option<Vec<String>>,
    /// revision_numbers
    #[arg(long, num_args = 1..)]
    pub revision_numbers: Option<Vec<String>>,
    /// batch_numbers
    #[arg(long, num_args = 1..)]
    pub batch_numbers: Option<Vec<String>>,
    /// duration_min
    #[arg(long)]
    pub duration_min: Option<String>,
    /// duration_max
    #[arg(long)]
    pub duration_max: Option<String>,
    /// started_after
    #[arg(long)]
    pub started_after: Option<String>,
    /// started_before
    #[arg(long)]
    pub started_before: Option<String>,
    /// ended_after
    #[arg(long)]
    pub ended_after: Option<String>,
    /// ended_before
    #[arg(long)]
    pub ended_before: Option<String>,
    /// created_after
    #[arg(long)]
    pub created_after: Option<String>,
    /// created_before
    #[arg(long)]
    pub created_before: Option<String>,
    /// created_by_user_ids
    #[arg(long, num_args = 1..)]
    pub created_by_user_ids: Option<Vec<String>>,
    /// created_by_station_ids
    #[arg(long, num_args = 1..)]
    pub created_by_station_ids: Option<Vec<String>>,
    /// operated_by_ids
    #[arg(long, num_args = 1..)]
    pub operated_by_ids: Option<Vec<String>>,
    /// Maximum number of runs to return per page.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
    /// Field to sort results by.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
    /// Filter runs by custom metadata. Supports up to 5 keys per request. Per-key operators: string `{in: [...]}`/`{contains: "..."}`, number `{gte, lte, gt, lt, eq}`, bool `{eq: true|false}`.
    #[arg(long)]
    pub metadata: Option<String>,
    /// When true, includes the run metadata array in the response. Defaults to false to keep payloads small.
    #[arg(long)]
    pub include_metadata: Option<bool>,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete runs
#[derive(Args)]
pub struct RmArgs {
    /// Run IDs to delete.
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get run
#[derive(Args)]
pub struct GetArgs {
    /// ID of the run to retrieve.
    #[arg(long)]
    pub id: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update run
#[derive(Args)]
pub struct UpdateArgs {
    /// Unique identifier of the run to update.
    #[arg(long)]
    pub id: String,
    /// Array of upload IDs to attach to the run.
    #[arg(long, num_args = 1..)]
    pub attachments: Option<Vec<String>>,
}

// ---------------------------------------------------------------------------
// CreateAttachment
// ---------------------------------------------------------------------------

/// Attach file to run
#[derive(Args)]
pub struct CreateAttachmentArgs {
    /// Unique identifier of the run to attach the file to.
    #[arg(long)]
    pub id: String,
    /// File name including extension (e.g. "report.pdf"). Used to determine content type and display name.
    #[arg(long)]
    pub name: String,
}

// ---------------------------------------------------------------------------
// UpdateMetadata
// ---------------------------------------------------------------------------

/// Update run metadata
#[derive(Args)]
pub struct UpdateMetadataArgs {
    /// Unique identifier of the run to update.
    #[arg(long)]
    pub id: String,
    /// Custom metadata to upsert on the run. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key. (JSON string)
    #[arg(long)]
    pub metadata: Option<String>,
}

pub async fn execute(client: &TofuPilot, cmd: RunsCommand, json_mode: bool) -> i32 {
    match cmd {
        RunsCommand::Create(args) => execute_create(client, args, json_mode).await,
        RunsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        RunsCommand::Rm(args) => execute_delete(client, args, json_mode).await,
        RunsCommand::Get(args) => execute_get(client, args, json_mode).await,
        RunsCommand::Update(args) => execute_update(client, args, json_mode).await,
        RunsCommand::CreateAttachment(args) => {
            execute_create_attachment(client, args, json_mode).await
        }
        RunsCommand::UpdateMetadata(args) => execute_update_metadata(client, args, json_mode).await,
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.runs().create();
    match serde_json::from_value::<LogGetOutcome>(serde_json::Value::String(args.outcome.clone())) {
        Ok(parsed) => {
            builder = builder.outcome(parsed);
        }
        Err(e) => {
            eprintln!("Invalid value for --outcome: {e}");
            return 1;
        }
    }
    builder = builder.procedure_id(&args.procedure_id);
    if let Some(ref v) = args.deployment_id {
        builder = builder.deployment_id(v);
    }
    if let Some(ref v) = args.procedure_version {
        builder = builder.procedure_version(v);
    }
    if let Some(ref v) = args.operated_by {
        builder = builder.operated_by(v);
    }
    match args.started_at.parse::<chrono::DateTime<chrono::Utc>>() {
        Ok(dt) => {
            builder = builder.started_at(dt);
        }
        Err(e) => {
            eprintln!("Invalid datetime for --started-at: {e}");
            return 1;
        }
    }
    match args.ended_at.parse::<chrono::DateTime<chrono::Utc>>() {
        Ok(dt) => {
            builder = builder.ended_at(dt);
        }
        Err(e) => {
            eprintln!("Invalid datetime for --ended-at: {e}");
            return 1;
        }
    }
    builder = builder.serial_number(&args.serial_number);
    if let Some(ref v) = args.part_number {
        builder = builder.part_number(v);
    }
    if let Some(ref v) = args.revision_number {
        builder = builder.revision_number(v);
    }
    if let Some(ref v) = args.batch_number {
        builder = builder.batch_number(v);
    }
    if let Some(ref v) = args.sub_units {
        builder = builder.sub_units(v.clone());
    }
    if let Some(ref v) = args.docstring {
        builder = builder.docstring(v);
    }
    if let Some(ref v) = args.phases {
        match serde_json::from_str::<Vec<RunCreatePhases>>(v) {
            Ok(parsed) => {
                builder = builder.phases(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --phases: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.logs {
        match serde_json::from_str::<Vec<RunCreateLogs>>(v) {
            Ok(parsed) => {
                builder = builder.logs(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --logs: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.unit_metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.unit_metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --unit-metadata: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.runs().list();
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    if let Some(ref v) = args.outcomes {
        let mut parsed: Vec<LogGetOutcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<LogGetOutcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.outcomes(parsed);
    }
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    if let Some(ref v) = args.procedure_versions {
        builder = builder.procedure_versions(v.clone());
    }
    if let Some(ref v) = args.deployment_ids {
        builder = builder.deployment_ids(v.clone());
    }
    if let Some(ref v) = args.environments {
        let mut parsed: Vec<Environment> = Vec::new();
        for s in v {
            match serde_json::from_value::<Environment>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --environments: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.environments(parsed);
    }
    if let Some(ref v) = args.serial_numbers {
        builder = builder.serial_numbers(v.clone());
    }
    if let Some(ref v) = args.samples {
        let mut parsed: Vec<Sample> = Vec::new();
        for s in v {
            match serde_json::from_value::<Sample>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --samples: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.samples(parsed);
    }
    if let Some(ref v) = args.part_numbers {
        builder = builder.part_numbers(v.clone());
    }
    if let Some(ref v) = args.revision_numbers {
        builder = builder.revision_numbers(v.clone());
    }
    if let Some(ref v) = args.batch_numbers {
        builder = builder.batch_numbers(v.clone());
    }
    if let Some(ref v) = args.duration_min {
        builder = builder.duration_min(v);
    }
    if let Some(ref v) = args.duration_max {
        builder = builder.duration_max(v);
    }
    if let Some(ref v) = args.started_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.started_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --started-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.started_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.started_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --started-before: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.ended_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.ended_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --ended-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.ended_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.ended_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --ended-before: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-before: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_by_user_ids {
        builder = builder.created_by_user_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_station_ids {
        builder = builder.created_by_station_ids(v.clone());
    }
    if let Some(ref v) = args.operated_by_ids {
        builder = builder.operated_by_ids(v.clone());
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<RunListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_by(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_order(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.include_metadata {
        builder = builder.include_metadata(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"]
                    .as_array()
                    .map(|a| a.as_slice())
                    .unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 8,
                        truncate: true,
                    },
                    display::Column {
                        header: "Outcome",
                        path: "outcome",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Procedure",
                        path: "procedure.name",
                        format: "",
                        width: 20,
                        truncate: true,
                    },
                    display::Column {
                        header: "Serial",
                        path: "unit.serial_number",
                        format: "",
                        width: 16,
                        truncate: true,
                    },
                    display::Column {
                        header: "Duration",
                        path: "duration",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Started",
                        path: "started_at",
                        format: "relative",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.runs().delete();
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.runs().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let fields: &[(&str, &str, &str)] = &[
                    ("ID", "id", ""),
                    ("Outcome", "outcome", ""),
                    ("Procedure", "procedure.name", ""),
                    ("Unit", "unit.serial_number", ""),
                    ("Part", "unit.part.number", ""),
                    ("Revision", "unit.part.revision.number", ""),
                    ("Duration", "duration", ""),
                    ("Started", "started_at", ""),
                    ("Ended", "ended_at", ""),
                ];
                display::print_detail(&value, fields);
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.runs().update();
    builder = builder.id(&args.id);
    if let Some(ref v) = args.attachments {
        builder = builder.attachments(v.clone());
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_create_attachment(
    client: &TofuPilot,
    args: CreateAttachmentArgs,
    json_mode: bool,
) -> i32 {
    let mut builder = client.runs().create_attachment();
    builder = builder.id(&args.id);
    builder = builder.name(&args.name);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_update_metadata(
    client: &TofuPilot,
    args: UpdateMetadataArgs,
    json_mode: bool,
) -> i32 {
    let mut builder = client.runs().update_metadata();
    builder = builder.id(&args.id);
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}
