// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
use tofupilot_sdk::TofuPilot;
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use crate::display;

/// Stations commands.
#[derive(Subcommand)]
pub enum StationsCommand {
    /// Create station
    Create(CreateArgs),
    /// List and filter stations
    Ls(LsArgs),
    /// Get current station
    GetCurrent(GetCurrentArgs),
    /// Get station
    Get(GetArgs),
    /// Update station
    Update(UpdateArgs),
    /// Remove station
    Rm(RmArgs),
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create station
#[derive(Args)]
pub struct CreateArgs {
    /// Name of the station
    #[arg(long)]
    pub name: String,
    /// Optional procedure ID to link the station to
    #[arg(long)]
    pub procedure_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter stations
#[derive(Args)]
pub struct LsArgs {
    /// Number of stations to return per page
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
}

// ---------------------------------------------------------------------------
// GetCurrent
// ---------------------------------------------------------------------------

/// Get current station
#[derive(Args)]
pub struct GetCurrentArgs {
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get station
#[derive(Args)]
pub struct GetArgs {
    /// Unique identifier of the station to retrieve
    #[arg(long)]
    pub id: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update station
#[derive(Args)]
pub struct UpdateArgs {
    /// Unique identifier of the station to update
    #[arg(long)]
    pub id: String,
    /// New name for the station
    #[arg(long)]
    pub name: Option<String>,
    /// Upload ID for the station image, or empty string to remove image
    #[arg(long)]
    pub image_id: Option<String>,
    /// Team ID to assign this station to, or null to unassign
    #[arg(long)]
    pub team_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Remove station
#[derive(Args)]
pub struct RmArgs {
    /// Unique identifier of the station to remove
    #[arg(long)]
    pub id: String,
}


pub async fn execute(client: &TofuPilot, cmd: StationsCommand, json_mode: bool) -> i32 {
    match cmd {
        StationsCommand::Create(args) => execute_create(client, args, json_mode).await,
        StationsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        StationsCommand::GetCurrent(args) => execute_get_current(client, args, json_mode).await,
        StationsCommand::Get(args) => execute_get(client, args, json_mode).await,
        StationsCommand::Update(args) => execute_update(client, args, json_mode).await,
        StationsCommand::Rm(args) => execute_remove(client, args, json_mode).await,
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.stations().create();
    builder = builder.name(&args.name);
    if let Some(ref v) = args.procedure_id {
        builder = builder.procedure_id(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.stations().list();
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"].as_array().map(|a| a.as_slice()).unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 8,
                        truncate: true,
                    },
                    display::Column {
                        header: "Name",
                        path: "name",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Procedures",
                        path: "procedures_count",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_get_current(client: &TofuPilot, _args: GetCurrentArgs, json_mode: bool) -> i32 {
    let builder = client.stations().get_current();
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.stations().get();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.stations().update();
    builder = builder.id(&args.id);
    if let Some(ref v) = args.name {
        builder = builder.name(v);
    }
    if let Some(ref v) = args.image_id {
        builder = builder.image_id(v);
    }
    if let Some(ref v) = args.team_id {
        builder = builder.team_id(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_remove(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.stations().remove();
    builder = builder.id(&args.id);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

