// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use crate::display;
use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Units commands.
#[derive(Subcommand)]
pub enum UnitsCommand {
    /// Create unit
    Create(CreateArgs),
    /// List and filter units
    Ls(LsArgs),
    /// Delete units
    Rm(RmArgs),
    /// Get unit
    Get(GetArgs),
    /// Update unit
    Update(UpdateArgs),
    /// Add sub-unit
    AddChild(AddChildArgs),
    /// Remove sub-unit
    RemoveChild(RemoveChildArgs),
    /// Attach file to unit
    CreateAttachment(CreateAttachmentArgs),
    /// Delete unit attachments
    DeleteAttachment(DeleteAttachmentArgs),
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create unit
#[derive(Args)]
pub struct CreateArgs {
    /// Unique serial number identifier for the unit. Must be unique within the organization.
    #[arg(long)]
    pub serial_number: String,
    /// Component part number that defines what type of unit this is. If the part does not exist, it will be created.
    #[arg(long)]
    pub part_number: String,
    /// Hardware revision identifier for the specific version of the part. If the revision does not exist, it will be created.
    #[arg(long)]
    pub revision_number: String,
    /// Reference-sample classification. 'golden' marks a known-good reference unit; 'failing' marks a known-faulty reference unit. Both are excluded from production analytics aggregates (FPY, Cpk, throughput) by default. Omit or null for regular production units.
    #[arg(long)]
    pub sample: Option<String>,
    /// Custom metadata to attach to the unit (max 50 keys per unit). Plain object of key/value pairs; values can be string, number, or boolean. Type is detected from the value. (JSON string)
    #[arg(long)]
    pub metadata: Option<String>,
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List and filter units
#[derive(Args)]
pub struct LsArgs {
    /// search_query
    #[arg(long)]
    pub search_query: Option<String>,
    /// ids
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
    /// serial_numbers
    #[arg(long, num_args = 1..)]
    pub serial_numbers: Option<Vec<String>>,
    /// part_numbers
    #[arg(long, num_args = 1..)]
    pub part_numbers: Option<Vec<String>>,
    /// revision_numbers
    #[arg(long, num_args = 1..)]
    pub revision_numbers: Option<Vec<String>>,
    /// batch_numbers
    #[arg(long, num_args = 1..)]
    pub batch_numbers: Option<Vec<String>>,
    /// procedure_ids
    #[arg(long, num_args = 1..)]
    pub procedure_ids: Option<Vec<String>>,
    /// outcomes
    #[arg(long, num_args = 1..)]
    pub outcomes: Option<Vec<String>>,
    /// started_after
    #[arg(long)]
    pub started_after: Option<String>,
    /// started_before
    #[arg(long)]
    pub started_before: Option<String>,
    /// latest_only
    #[arg(long)]
    pub latest_only: Option<bool>,
    /// run_count_min
    #[arg(long)]
    pub run_count_min: Option<i64>,
    /// run_count_max
    #[arg(long)]
    pub run_count_max: Option<i64>,
    /// created_after
    #[arg(long)]
    pub created_after: Option<String>,
    /// created_before
    #[arg(long)]
    pub created_before: Option<String>,
    /// created_by_user_ids
    #[arg(long, num_args = 1..)]
    pub created_by_user_ids: Option<Vec<String>>,
    /// created_by_station_ids
    #[arg(long, num_args = 1..)]
    pub created_by_station_ids: Option<Vec<String>>,
    /// exclude_units_with_parent
    #[arg(long)]
    pub exclude_units_with_parent: Option<bool>,
    /// samples
    #[arg(long, num_args = 1..)]
    pub samples: Option<Vec<String>>,
    /// Maximum number of units to return.
    #[arg(long)]
    pub limit: Option<i64>,
    /// cursor
    #[arg(long)]
    pub cursor: Option<i64>,
    /// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
    #[arg(long)]
    pub sort_by: Option<String>,
    /// Sort order direction.
    #[arg(long)]
    pub sort_order: Option<String>,
    /// Filter units by custom metadata. Supports up to 5 keys per request. Per-key operators: string `{in: [...]}`/`{contains: "..."}`, number `{gte, lte, gt, lt, eq}`, bool `{eq: true|false}`.
    #[arg(long)]
    pub metadata: Option<String>,
    /// When true, includes the unit metadata array in the response. Defaults to false to keep payloads small.
    #[arg(long)]
    pub include_metadata: Option<bool>,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete units
#[derive(Args)]
pub struct RmArgs {
    /// Array of unit serial numbers to delete.
    #[arg(long, num_args = 1..)]
    pub serial_numbers: Option<Vec<String>>,
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get unit
#[derive(Args)]
pub struct GetArgs {
    /// Serial number of the unit to retrieve.
    #[arg(long)]
    pub serial_number: String,
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/// Update unit
#[derive(Args)]
pub struct UpdateArgs {
    /// Serial number of the unit to update.
    #[arg(long)]
    pub serial_number: String,
    /// New serial number for the unit.
    #[arg(long)]
    pub new_serial_number: Option<String>,
    /// New part number for the unit.
    #[arg(long)]
    pub part_number: Option<String>,
    /// New revision number for the unit.
    #[arg(long)]
    pub revision_number: Option<String>,
    /// New batch number for the unit. Set to null to remove batch.
    #[arg(long)]
    pub batch_number: Option<String>,
    /// Array of upload IDs to attach to the unit.
    #[arg(long, num_args = 1..)]
    pub attachments: Option<Vec<String>>,
    /// Reference-sample classification. 'golden' marks a known-good reference unit; 'failing' marks a known-faulty reference unit. Both are excluded from production analytics by default. Set to null to clear and treat as a production unit.
    #[arg(long)]
    pub sample: Option<String>,
    /// Custom metadata to upsert on the unit. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key. (JSON string)
    #[arg(long)]
    pub metadata: Option<String>,
}

// ---------------------------------------------------------------------------
// AddChild
// ---------------------------------------------------------------------------

/// Add sub-unit
#[derive(Args)]
pub struct AddChildArgs {
    /// Serial number of the parent unit
    #[arg(long)]
    pub serial_number: String,
    /// Serial number of the sub-unit to add
    #[arg(long)]
    pub child_serial_number: String,
}

// ---------------------------------------------------------------------------
// RemoveChild
// ---------------------------------------------------------------------------

/// Remove sub-unit
#[derive(Args)]
pub struct RemoveChildArgs {
    /// Serial number of the parent unit
    #[arg(long)]
    pub serial_number: String,
    /// Serial number of the sub-unit to remove
    #[arg(long)]
    pub child_serial_number: Option<String>,
}

// ---------------------------------------------------------------------------
// CreateAttachment
// ---------------------------------------------------------------------------

/// Attach file to unit
#[derive(Args)]
pub struct CreateAttachmentArgs {
    /// Serial number of the unit to attach the file to. Matched case-insensitively.
    #[arg(long)]
    pub serial_number: String,
    /// File name including extension (e.g. "calibration.pdf"). Used to determine content type and display name.
    #[arg(long)]
    pub name: String,
}

// ---------------------------------------------------------------------------
// DeleteAttachment
// ---------------------------------------------------------------------------

/// Delete unit attachments
#[derive(Args)]
pub struct DeleteAttachmentArgs {
    /// Serial number of the unit. Matched case-insensitively.
    #[arg(long)]
    pub serial_number: String,
    /// Attachment IDs to delete
    #[arg(long, num_args = 1..)]
    pub ids: Option<Vec<String>>,
}

pub async fn execute(client: &TofuPilot, cmd: UnitsCommand, json_mode: bool) -> i32 {
    match cmd {
        UnitsCommand::Create(args) => execute_create(client, args, json_mode).await,
        UnitsCommand::Ls(args) => execute_list(client, args, json_mode).await,
        UnitsCommand::Rm(args) => execute_delete(client, args, json_mode).await,
        UnitsCommand::Get(args) => execute_get(client, args, json_mode).await,
        UnitsCommand::Update(args) => execute_update(client, args, json_mode).await,
        UnitsCommand::AddChild(args) => execute_add_child(client, args, json_mode).await,
        UnitsCommand::RemoveChild(args) => execute_remove_child(client, args, json_mode).await,
        UnitsCommand::CreateAttachment(args) => {
            execute_create_attachment(client, args, json_mode).await
        }
        UnitsCommand::DeleteAttachment(args) => {
            execute_delete_attachment(client, args, json_mode).await
        }
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().create();
    builder = builder.serial_number(&args.serial_number);
    builder = builder.part_number(&args.part_number);
    builder = builder.revision_number(&args.revision_number);
    if let Some(ref v) = args.sample {
        match serde_json::from_value::<Sample>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sample(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sample: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().list();
    if let Some(ref v) = args.search_query {
        builder = builder.search_query(v);
    }
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    if let Some(ref v) = args.serial_numbers {
        builder = builder.serial_numbers(v.clone());
    }
    if let Some(ref v) = args.part_numbers {
        builder = builder.part_numbers(v.clone());
    }
    if let Some(ref v) = args.revision_numbers {
        builder = builder.revision_numbers(v.clone());
    }
    if let Some(ref v) = args.batch_numbers {
        builder = builder.batch_numbers(v.clone());
    }
    if let Some(ref v) = args.procedure_ids {
        builder = builder.procedure_ids(v.clone());
    }
    if let Some(ref v) = args.outcomes {
        let mut parsed: Vec<RunGetOutcome> = Vec::new();
        for s in v {
            match serde_json::from_value::<RunGetOutcome>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --outcomes: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.outcomes(parsed);
    }
    if let Some(ref v) = args.started_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.started_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --started-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.started_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.started_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --started-before: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.latest_only {
        builder = builder.latest_only(v);
    }
    if let Some(v) = args.run_count_min {
        builder = builder.run_count_min(v);
    }
    if let Some(v) = args.run_count_max {
        builder = builder.run_count_max(v);
    }
    if let Some(ref v) = args.created_after {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_after(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-after: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_before {
        match v.parse::<chrono::DateTime<chrono::Utc>>() {
            Ok(dt) => {
                builder = builder.created_before(dt);
            }
            Err(e) => {
                eprintln!("Invalid datetime for --created-before: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.created_by_user_ids {
        builder = builder.created_by_user_ids(v.clone());
    }
    if let Some(ref v) = args.created_by_station_ids {
        builder = builder.created_by_station_ids(v.clone());
    }
    if let Some(v) = args.exclude_units_with_parent {
        builder = builder.exclude_units_with_parent(v);
    }
    if let Some(ref v) = args.samples {
        let mut parsed: Vec<Sample> = Vec::new();
        for s in v {
            match serde_json::from_value::<Sample>(serde_json::Value::String(s.clone())) {
                Ok(val) => parsed.push(val),
                Err(e) => {
                    eprintln!("Invalid value '{}' for --samples: {e}", s);
                    return 1;
                }
            }
        }
        builder = builder.samples(parsed);
    }
    if let Some(v) = args.limit {
        builder = builder.limit(v);
    }
    if let Some(v) = args.cursor {
        builder = builder.cursor(v);
    }
    if let Some(ref v) = args.sort_by {
        match serde_json::from_value::<UnitListSortBy>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_by(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-by: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.sort_order {
        match serde_json::from_value::<ListSortOrder>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sort_order(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sort-order: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    if let Some(v) = args.include_metadata {
        builder = builder.include_metadata(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let items = value["data"]
                    .as_array()
                    .map(|a| a.as_slice())
                    .unwrap_or(&[]);
                let columns = &[
                    display::Column {
                        header: "ID",
                        path: "id",
                        format: "",
                        width: 8,
                        truncate: true,
                    },
                    display::Column {
                        header: "Serial",
                        path: "serial_number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Part",
                        path: "part.number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Revision",
                        path: "part.revision.number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Batch",
                        path: "batch.number",
                        format: "",
                        width: 0,
                        truncate: false,
                    },
                    display::Column {
                        header: "Created",
                        path: "created_at",
                        format: "relative",
                        width: 0,
                        truncate: false,
                    },
                ];
                display::print_table(items, columns);
                if let Some(true) = value["meta"]["has_more"].as_bool() {
                    if let Some(cursor) = value["meta"]["next_cursor"].as_i64() {
                        eprintln!("  ... more results available (--cursor {cursor})");
                    }
                }
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().delete();
    if let Some(ref v) = args.serial_numbers {
        builder = builder.serial_numbers(v.clone());
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().get();
    builder = builder.serial_number(&args.serial_number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_update(client: &TofuPilot, args: UpdateArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().update();
    builder = builder.serial_number(&args.serial_number);
    if let Some(ref v) = args.new_serial_number {
        builder = builder.new_serial_number(v);
    }
    if let Some(ref v) = args.part_number {
        builder = builder.part_number(v);
    }
    if let Some(ref v) = args.revision_number {
        builder = builder.revision_number(v);
    }
    if let Some(ref v) = args.batch_number {
        builder = builder.batch_number(v);
    }
    if let Some(ref v) = args.attachments {
        builder = builder.attachments(v.clone());
    }
    if let Some(ref v) = args.sample {
        match serde_json::from_value::<Sample>(serde_json::Value::String(v.clone())) {
            Ok(parsed) => {
                builder = builder.sample(parsed);
            }
            Err(e) => {
                eprintln!("Invalid value for --sample: {e}");
                return 1;
            }
        }
    }
    if let Some(ref v) = args.metadata {
        match serde_json::from_str::<std::collections::HashMap<String, serde_json::Value>>(v) {
            Ok(parsed) => {
                builder = builder.metadata(parsed);
            }
            Err(e) => {
                eprintln!("Invalid JSON for --metadata: {e}");
                return 1;
            }
        }
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_add_child(client: &TofuPilot, args: AddChildArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().add_child();
    builder = builder.serial_number(&args.serial_number);
    builder = builder.child_serial_number(&args.child_serial_number);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_remove_child(client: &TofuPilot, args: RemoveChildArgs, json_mode: bool) -> i32 {
    let mut builder = client.units().remove_child();
    builder = builder.serial_number(&args.serial_number);
    if let Some(ref v) = args.child_serial_number {
        builder = builder.child_serial_number(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_create_attachment(
    client: &TofuPilot,
    args: CreateAttachmentArgs,
    json_mode: bool,
) -> i32 {
    let mut builder = client.units().create_attachment();
    builder = builder.serial_number(&args.serial_number);
    builder = builder.name(&args.name);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

async fn execute_delete_attachment(
    client: &TofuPilot,
    args: DeleteAttachmentArgs,
    json_mode: bool,
) -> i32 {
    let mut builder = client.units().delete_attachment();
    builder = builder.serial_number(&args.serial_number);
    if let Some(ref v) = args.ids {
        builder = builder.ids(v.clone());
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}
