// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Users commands.
#[derive(Subcommand)]
pub enum UsersCommand {
    /// List users
    Ls(LsArgs),
}

// ---------------------------------------------------------------------------
// Ls
// ---------------------------------------------------------------------------

/// List users
#[derive(Args)]
pub struct LsArgs {
    /// If true, returns only the current authenticated user
    #[arg(long)]
    pub current: Option<bool>,
}

pub async fn execute(client: &TofuPilot, cmd: UsersCommand, json_mode: bool) -> i32 {
    match cmd {
        UsersCommand::Ls(args) => execute_list(client, args, json_mode).await,
    }
}

async fn execute_list(client: &TofuPilot, args: LsArgs, json_mode: bool) -> i32 {
    let mut builder = client.users().list();
    if let Some(v) = args.current {
        builder = builder.current(v);
    }
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
