// Code generated by TofuPilot CLI Generator. DO NOT EDIT.

use clap::{Args, Subcommand};
#[allow(unused_imports)]
use tofupilot_sdk::types::*;
use tofupilot_sdk::TofuPilot;

/// Versions commands.
#[derive(Subcommand)]
pub enum VersionsCommand {
    /// Get procedure version
    Get(GetArgs),
    /// Delete procedure version
    Rm(RmArgs),
    /// Create procedure version
    Create(CreateArgs),
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

/// Get procedure version
#[derive(Args)]
pub struct GetArgs {
    /// ID of the procedure that owns this version.
    #[arg(long)]
    pub procedure_id: String,
    /// Version tag to retrieve.
    #[arg(long)]
    pub tag: String,
}

// ---------------------------------------------------------------------------
// Rm
// ---------------------------------------------------------------------------

/// Delete procedure version
#[derive(Args)]
pub struct RmArgs {
    /// ID of the procedure that owns this version
    #[arg(long)]
    pub procedure_id: String,
    /// Version tag to delete
    #[arg(long)]
    pub tag: String,
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/// Create procedure version
#[derive(Args)]
pub struct CreateArgs {
    /// The ID of the procedure this version belongs to
    #[arg(long)]
    pub procedure_id: String,
    /// The version tag
    #[arg(long)]
    pub tag: String,
}

pub async fn execute(client: &TofuPilot, cmd: VersionsCommand, json_mode: bool) -> i32 {
    match cmd {
        VersionsCommand::Get(args) => execute_get(client, args, json_mode).await,
        VersionsCommand::Rm(args) => execute_delete(client, args, json_mode).await,
        VersionsCommand::Create(args) => execute_create(client, args, json_mode).await,
    }
}

async fn execute_get(client: &TofuPilot, args: GetArgs, json_mode: bool) -> i32 {
    let mut builder = client.versions().get();
    builder = builder.procedure_id(&args.procedure_id);
    builder = builder.tag(&args.tag);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                // No display config for this operation: fall back to the
                // JSON payload so the command never succeeds silently.
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_delete(client: &TofuPilot, args: RmArgs, json_mode: bool) -> i32 {
    let mut builder = client.versions().delete();
    builder = builder.procedure_id(&args.procedure_id);
    builder = builder.tag(&args.tag);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Deleted version{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}

async fn execute_create(client: &TofuPilot, args: CreateArgs, json_mode: bool) -> i32 {
    let mut builder = client.versions().create();
    builder = builder.procedure_id(&args.procedure_id);
    builder = builder.tag(&args.tag);
    match builder.send().await {
        Ok(res) => {
            if json_mode {
                println!("{}", serde_json::to_string_pretty(&res).unwrap_or_default());
            } else {
                let value = serde_json::to_value(&res).unwrap_or_default();
                let id = value["id"]
                    .as_str()
                    .map(|s| format!(" {s}"))
                    .unwrap_or_default();
                crate::log::success(&format!("Created version{id}"));
            }
            0
        }
        Err(e) => {
            if json_mode {
                eprintln!(
                    "{}",
                    serde_json::json!({ "type": "error", "message": e.to_string() })
                );
            } else {
                eprintln!("{e}");
            }
            1
        }
    }
}
